def REPO = ''
def PACKAGE = ''
def IS_MOVE = 'false'
def IS_DELETE = 'false'
def MOVE_TO_REPO = ''
def PKG_PATH = ''

pipeline {
    agent any
    options {
        skipDefaultCheckout()
        timestamps()
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    checkout scm

                    def currentCommit = sh(returnStdout: true, script: 'git rev-parse @').trim()
//                     def lastMergeCommit = sh(returnStdout: true, script: 'git log --merges --oneline --format=format:%H -n 1').trim()

                    echo "currentCommit: ${currentCommit}"
//                     echo "lastMergeCommit: ${lastMergeCommit}"

//                     if ( currentCommit == lastMergeCommit ) {
//                     }
                    
                    def changedFilesStatus = sh(returnStdout: true, script: "git show --pretty=format: --name-status ${currentCommit}").tokenize('\n')
                    echo "changedFilesStatus: " + changedFilesStatus
                    
                    for (int i = 0; i < changedFilesStatus.size(); i++) {
                        def entry = changedFilesStatus[i].split()
                        def status = entry[0]
                        def filePath = entry[1]
                        def buildInfo = []
                        echo "filePath: ${filePath}"
                        echo "status: ${status}"
                        if ( filePath.contains('PKGBUILD') ){
                            PKG_PATH = filePath.minus('/PKGBUILD')
                            buildInfo = PKG_PATH.tokenize('/')
                            PACKAGE = buildInfo[0]
                            def gitRepo = buildInfo[2]
                            if ( gitRepo.contains('staging') ){
                                REPO = 'goblins'
                                if ( status == 'D' ){
                                    IS_MOVE = 'true'
                                    if ( fileExists("${PACKAGE}/repos/testing-x86_64") || fileExists("${PACKAGE}/repos/testing-any") ){
                                        MOVE_TO_REPO = 'gremlins'
                                    }
                                }
                            } else if ( gitRepo.contains('testing') ){
                                REPO = 'gremlins'
                                if ( status == 'D' ){
                                    IS_MOVE = 'true'
                                    if ( fileExists("${PACKAGE}/repos/core-x86_64") || fileExists("${PACKAGE}/repos/core-any") ){
                                        MOVE_TO_REPO = 'system'
                                    } else if ( fileExists("${PACKAGE}/repos/extra-x86_64") || fileExists("${PACKAGE}/repos/extra-any") ){
                                        MOVE_TO_REPO = 'world'
                                    }
                                }
                            } else if ( gitRepo.contains('core') ){
                                REPO = 'system'
                                if ( status == 'D' ){
                                    IS_DELETE = 'true'
                                }
                            } else if ( gitRepo.contains('extra') ){
                                REPO = 'world'
                                if ( status == 'D' ){
                                    IS_DELETE = 'true'
                                }
                            }
                        }
                    }
                    echo "PACKAGE: ${PACKAGE}"
                    echo "REPO: ${REPO}"
                    echo "IS_MOVE: ${IS_MOVE} MOVE_TO_REPO: ${MOVE_TO_REPO}"
                    echo "IS_DELETE: ${IS_DELETE}"
                }
            }
        }
        stage('Build') {
            environment {
                BUILDBOT_GPGP = credentials('BUILDBOT_GPGP')
            }
            when {
                expression { return  IS_MOVE == 'false' }
                expression { return  IS_DELETE == 'false' }
            }
            steps {
                script {
                    dir("${PKG_PATH}") {
                        echo "buildpkg2 -r ${REPO}"
                    }
                }
            }
            post {
                success {
                    script {
                        dir("${PKG_PATH}") {
                            echo "deploypkg2 -a -d ${REPO}"
                        }
                    }
                }
            }
        }
        stage('Move') {
            when {
                expression { return  IS_MOVE == 'true' }
                expression { return  IS_DELETE == 'false' }
            }
            steps {
                echo "deploypkg2-${REPO} -m -p ${PKG_PATH} -s ${REPO} -d ${MOVE_TO_REPO}"
            }
        }
        stage('Delete') {
            when {
                expression { return  IS_MOVE == 'false' }
                expression { return  IS_DELETE == 'true' }
            }
            steps {
                echo "deploypkg2-${REPO} -r -d ${REPO} -p ${PACKAGE}/trunk"
            }
        }
    }
}
